import Sidebar from "@/components/Sidebar";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div className="flex h-full bg-white ">
          <div className="hidden md:block">
            <Sidebar />
          </div>
          <main className="flex-1 flex flex-col overflow-hidden w-full md:w-auto">
            {children}
          </main>
        </div>
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
